name: padelio-app
services:
  order-service:
    container_name: order-service
    platform: linux/amd64
    image: masadamsahid/padelio-order-service:8
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - .env